name: Deploy

on:
  workflow_run:
    workflows: ['Tests']
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build
      - name: Install Railway CLI
        run: pnpm add -g @railway/cli --config allow-scripts=true
      - name: pnpm builds approved
        run: pnpm approve-builds -g
      - name: Link Railway Project
        run: railway link 3f88f1ce-44ee-4dae-8bd3-6a963b974c40
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      - name: Deploy to Railway
        run: railway up --detach --verbose # update this to the name of your service!
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
