name: Deploy

on:
  workflow_run:
    workflows: ['Tests']
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build
      - name: Install Railway CLI
        run: |
          pnpm add -g @railway/cli
          pnpm approve-builds -g
      - name: Deploy to Railway
        run: railway up --service="emoji-generator" --project="1731d95f-0880-4e29-8ad7-d8cadbbfc184"  # update this to the name of your service!
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
